import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lab4
 */
public class from_barang extends javax.swing.JFrame {
    private DefaultTableModel model;


    /**
     * Creates new form from_barang
     */
    public from_barang() {
        initComponents();
        loadData();
        kosong();
        TampilComboJenis();
        setEnablefalse();
        
    }
    
    public void setEnablefalse(){
       txtkodebarang.setEnabled(false);
       txtnamabarang.setEnabled(false);
       combobarang.setEnabled(false);
       txtjenisbarang.setEnabled(false);
       txtharganet.setEnabled(false);
       txthargajual.setEnabled(false);
       txtstok.setEnabled(false);
       btnsave.setEnabled(false);
       btnupdate.setEnabled(false);
       btndelete.setEnabled(false);
       btnclose.setEnabled(false);
       btnclose.setEnabled(false);
    }
    
     public void setEnabletrue(){
       txtkodebarang.setEnabled(true);
       txtnamabarang.setEnabled(true);
       combobarang.setEnabled(true);
       txtjenisbarang.setEnabled(true);
       txtharganet.setEnabled(true);
       txthargajual.setEnabled(true);
       txtstok.setEnabled(true);
       btnsave.setEnabled(true);
       btnupdate.setEnabled(true);
       btndelete.setEnabled(true);
       btnclose.setEnabled(true);
       btnclose.setEnabled(true);
    }
     
     public void TampilComboJenis(){
        try{
            String sql = "SELECT * FROM tbljenis";
            
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            
            while(r.next()){
                combobarang.addItem(r.getString("KodeJenis"));
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
        
        
       
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
     private void loadData (){
        
        model = new DefaultTableModel();
        
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        tabelbarang.setModel(model);
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Jenis Barang");
        model.addColumn("Harga Net");
        model.addColumn("Harga Jual");
        model.addColumn("Stok");
        
         try{
            String sql = "SELECT * FROM tblbarang";
           
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
           
            while(r.next()){
                model.addRow(new Object[]{
                    r.getString(1),
                    r.getString(2),
                    r.getString(3),
                    r.getString(4),
                    r.getString(5),
                    r.getString(6)
                });
            }
            tabelbarang.setModel(model);
        } catch(SQLException e){
            System.out.println("terjadi eror");
        }
    }
     
     private void kosong(){
        txtkodebarang.setText(null);
        txtnamabarang.setText(null);
        txtjenisbarang.setText(null);
        txtharganet.setText(null);
        txthargajual.setText(null);
        txtstok.setText(null);
        combobarang.setSelectedIndex(0);
    }
        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnaddnew = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelbarang = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtkodebarang = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtstok = new javax.swing.JTextField();
        txthargajual = new javax.swing.JTextField();
        txtharganet = new javax.swing.JTextField();
        txtjenisbarang = new javax.swing.JTextField();
        combobarang = new javax.swing.JComboBox<>();
        txtnamabarang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(75, 82, 126));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ENTRI DATA BARANG");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 230, -1));

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        btndelete.setBackground(new java.awt.Color(255, 0, 0));
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        btnaddnew.setText("Add New");
        btnaddnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddnewActionPerformed(evt);
            }
        });
        jPanel1.add(btnaddnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel1.add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, -1, -1));

        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 550, -1, -1));

        tabelbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelbarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelbarang);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 500, 160));

        jPanel2.setBackground(new java.awt.Color(229, 195, 166));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtkodebarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodebarangActionPerformed(evt);
            }
        });
        jPanel2.add(txtkodebarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 91, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Kode Barang");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
        jPanel2.add(txtstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 87, -1));
        jPanel2.add(txthargajual, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 245, -1));
        jPanel2.add(txtharganet, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 245, -1));
        jPanel2.add(txtjenisbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 245, -1));

        combobarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Kode Jenis Barang--", " " }));
        combobarang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combobarangItemStateChanged(evt);
            }
        });
        combobarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobarangActionPerformed(evt);
            }
        });
        jPanel2.add(combobarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 245, -1));
        jPanel2.add(txtnamabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 245, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Nama Barang");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 90, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Kode Jenis Barang");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Jenis Barang");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 80, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Harga Jual");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 60, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Stok");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 37, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Harga Net");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 97, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 400, 270));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 560, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        String kode_barang = txtkodebarang.getText();
        String nama_barang = txtnamabarang.getText();
        String jenis_barang = txtjenisbarang.getText();
        String harga_net = txtharganet.getText();
        String harga_jual = txthargajual.getText();
        String stok = txtstok.getText();
        
        String KJ=combobarang.getSelectedItem().toString();
        if ("".equals(kode_barang) || 
                "".equals(nama_barang) ||
                "".equals(jenis_barang) || 
                "".equals(harga_net) ||
                "".equals(harga_jual) ||
                "".equals(stok)||"".equals(KJ))
        {
            
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }else {
           
            try{
                Connection c = koneksi.getKoneksi();
                String sql = "INSERT INTO tblbarang VALUES (?, ?, ?, ?, ?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
               
                
                p.setString(1, kode_barang);
                p.setString(2, nama_barang);
                p.setString(3, KJ);
                p.setString(4, harga_net);
                p.setString(5, harga_jual);
                p.setString(6, stok);
               
          

                p.executeUpdate();
                p.close();
                
                JOptionPane.showMessageDialog(null, "Berhasil ditambah");
                
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }finally {
                loadData();
                kosong();
               setEnablefalse();
               btnaddnew.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        txtkodebarang.setText("");
        txtnamabarang.setText("");
        txtjenisbarang.setText("");
        txtharganet.setText("");
        txthargajual.setText("");
        txtstok.setText("");
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnaddnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddnewActionPerformed
        // TODO add your handling code here:
       setEnabletrue();
        btnaddnew.setEnabled(true);
    }//GEN-LAST:event_btnaddnewActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
           int i = tabelbarang.getSelectedRow();
        
        if(i == -1){
            //tidak ada baris terseleksi
            JOptionPane.showMessageDialog(this, "harap pilih data terlebih dahulu", "error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String kode_barang = (String) model.getValueAt(i, 0);
        String nama_barang = txtnamabarang.getText();
        String KJ = combobarang.getSelectedItem().toString();
        String harga_net = txtharganet.getText();
        String harga_jual = txthargajual.getText();
        String stok = txtstok.getText();
        
        try{
            
            Connection c = koneksi.getKoneksi();
            
            String sql = "UPDATE tblbarang SET NamaBarang = ?,KodeJenis = ?, HargaNet = ?, HargaJual = ? , Stok = ? WHERE KodeBarang = ?";
            
            PreparedStatement p = c.prepareStatement(sql);
            
            
                
                p.setString(1, nama_barang);
                p.setString(2, KJ);
                p.setString(3, harga_net);
                p.setString(4, harga_jual);
                p.setString(5, stok);
                p.setString(6, kode_barang);
                
            p.executeUpdate();
                p.close();
                
                JOptionPane.showMessageDialog(null,
                       "Ubah Data Berhasil");
                
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this,
                        e.getMessage());
                
            }finally{
            loadData();
            kosong();
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int i = tabelbarang.getSelectedRow();
        
        if(i == -1){
            JOptionPane.showMessageDialog(this, "Harap Pilih Data Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String kode_barang = (String) model.getValueAt(i, 0);
        
        try{
            Connection c = koneksi.getKoneksi();
            
           String sql = "DELETE FROM tblbarang WHERE KodeBarang=?";
                     
                     PreparedStatement p = c.prepareStatement(sql);
                     p.setString(1, kode_barang);
                     p.executeUpdate();
                     p.close();
                     
                     JOptionPane.showMessageDialog(null, "Hapus Data Berhasil");
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Terjadi Error"+e.getMessage());
        } finally{
            loadData();
            kosong();
        }
           
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
         dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void tabelbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelbarangMouseClicked
        // TODO add your handling code here:
        int baris = tabelbarang.getSelectedRow();
        if(baris == -1) {
            return ;
        }
        
        String kode_barang = tabelbarang.getValueAt(baris, 0).toString();
        txtkodebarang.setText(kode_barang);
        String nama_barang = tabelbarang.getValueAt(baris, 1).toString();
        txtnamabarang.setText(nama_barang);
        combobarang.setSelectedItem(tabelbarang.getValueAt(baris, 2).toString());
        String harga_net = tabelbarang.getValueAt(baris, 3).toString();
        txtharganet.setText(harga_net);
        String harga_jual = tabelbarang.getValueAt(baris, 4).toString();
        txthargajual.setText(harga_jual);
        String stok = tabelbarang.getValueAt(baris, 5).toString();
        txtstok.setText(stok);
    }//GEN-LAST:event_tabelbarangMouseClicked

    private void combobarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobarangActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_combobarangActionPerformed

    private void combobarangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combobarangItemStateChanged
        // TODO add your handling code here:
        try {
            String sql = "SELECT * FROM tbljenis WHERE KodeJenis='"+ combobarang.getSelectedItem().toString()+"'";
            
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            
            r.absolute(1);
            txtjenisbarang.setText(r.getString("Jenis"));       
        }catch (SQLException ex){
            
        }
    }//GEN-LAST:event_combobarangItemStateChanged

    private void txtkodebarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodebarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkodebarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(from_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(from_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(from_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(from_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new from_barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddnew;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> combobarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelbarang;
    private javax.swing.JTextField txthargajual;
    private javax.swing.JTextField txtharganet;
    private javax.swing.JTextField txtjenisbarang;
    private javax.swing.JTextField txtkodebarang;
    private javax.swing.JTextField txtnamabarang;
    private javax.swing.JTextField txtstok;
    // End of variables declaration//GEN-END:variables
}
