import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lab4
 */
public class from_barang extends javax.swing.JFrame {
    private DefaultTableModel model;


    /**
     * Creates new form from_barang
     */
    public from_barang() {
        initComponents();
        loadData();
        kosong();
        TampilComboJenis();
        setEnablefalse();
        
    }
    
    public void setEnablefalse(){
       txtkodebarang.setEnabled(false);
       txtnamabarang.setEnabled(false);
       combobarang.setEnabled(false);
       txtjenisbarang.setEnabled(false);
       txtharganet.setEnabled(false);
       txthargajual.setEnabled(false);
       txtstok.setEnabled(false);
       btnsave.setEnabled(false);
       btnupdate.setEnabled(false);
       btndelete.setEnabled(false);
       btnclose.setEnabled(false);
       btnclose.setEnabled(false);
    }
    
     public void setEnabletrue(){
       txtkodebarang.setEnabled(true);
       txtnamabarang.setEnabled(true);
       combobarang.setEnabled(true);
       txtjenisbarang.setEnabled(true);
       txtharganet.setEnabled(true);
       txthargajual.setEnabled(true);
       txtstok.setEnabled(true);
       btnsave.setEnabled(true);
       btnupdate.setEnabled(true);
       btndelete.setEnabled(true);
       btnclose.setEnabled(true);
       btnclose.setEnabled(true);
    }
     
     public void TampilComboJenis(){
        try{
            String sql = "SELECT * FROM tbljenis";
            
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            
            while(r.next()){
                combobarang.addItem(r.getString("KodeJenis"));
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
        
        
       
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
     private void loadData (){
        
        model = new DefaultTableModel();
        
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        tabelbarang.setModel(model);
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Jenis Barang");
        model.addColumn("Harga Net");
        model.addColumn("Harga Jual");
        model.addColumn("Stok");
        
         try{
            String sql = "SELECT * FROM tblbarang";
           
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
           
            while(r.next()){
                model.addRow(new Object[]{
                    r.getString(1),
                    r.getString(2),
                    r.getString(3),
                    r.getString(4),
                    r.getString(5),
                    r.getString(6)
                });
            }
            tabelbarang.setModel(model);
        } catch(SQLException e){
            System.out.println("terjadi eror");
        }
    }
     
     private void kosong(){
        txtkodebarang.setText(null);
        txtnamabarang.setText(null);
        txtjenisbarang.setText(null);
        txtharganet.setText(null);
        txthargajual.setText(null);
        txtstok.setText(null);
        combobarang.setSelectedIndex(0);
    }
        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelbarang = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btnaddnew = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtkodebarang = new javax.swing.JTextField();
        txtnamabarang = new javax.swing.JTextField();
        combobarang = new javax.swing.JComboBox<>();
        txtjenisbarang = new javax.swing.JTextField();
        txtharganet = new javax.swing.JTextField();
        txthargajual = new javax.swing.JTextField();
        txtstok = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Kode Barang");

        jLabel2.setText("Nama Barang");

        jLabel3.setText("Kode Jenis Barang");

        jLabel4.setText("Jenis Barang");

        jLabel5.setText("Harga Net");

        jLabel6.setText("Harga Jual");

        tabelbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelbarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelbarang);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("ENTRI DATA BARANG");

        btnaddnew.setText("Add New");
        btnaddnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddnewActionPerformed(evt);
            }
        });

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        jLabel8.setText("Stok");

        combobarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Kode Jenis Barang--", " " }));
        combobarang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combobarangItemStateChanged(evt);
            }
        });
        combobarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(btnaddnew)
                            .addGap(47, 47, 47)
                            .addComponent(btnsave)
                            .addGap(59, 59, 59)
                            .addComponent(btnupdate)
                            .addGap(43, 43, 43)
                            .addComponent(btndelete)
                            .addGap(52, 52, 52)
                            .addComponent(btncancel)
                            .addGap(50, 50, 50)
                            .addComponent(btnclose))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(22, 22, 22)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txthargajual, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtharganet, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtjenisbarang, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnamabarang, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combobarang, javax.swing.GroupLayout.Alignment.LEADING, 0, 245, Short.MAX_VALUE)
                                    .addComponent(txtstok, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtkodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtkodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(combobarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtjenisbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtharganet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txthargajual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtstok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndelete)
                    .addComponent(btncancel)
                    .addComponent(btnclose)
                    .addComponent(btnupdate)
                    .addComponent(btnsave)
                    .addComponent(btnaddnew))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        String kode_barang = txtkodebarang.getText();
        String nama_barang = txtnamabarang.getText();
        String jenis_barang = txtjenisbarang.getText();
        String harga_net = txtharganet.getText();
        String harga_jual = txthargajual.getText();
        String stok = txtstok.getText();
        
        String KJ=combobarang.getSelectedItem().toString();
        if ("".equals(kode_barang) || 
                "".equals(nama_barang) ||
                "".equals(jenis_barang) || 
                "".equals(harga_net) ||
                "".equals(harga_jual) ||
                "".equals(stok)||"".equals(KJ))
        {
            
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }else {
           
            try{
                Connection c = koneksi.getKoneksi();
                String sql = "INSERT INTO tblbarang VALUES (?, ?, ?, ?, ?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
               
                
                p.setString(1, kode_barang);
                p.setString(2, nama_barang);
                p.setString(3, KJ);
                p.setString(4, harga_net);
                p.setString(5, harga_jual);
                p.setString(6, stok);
               
          

                p.executeUpdate();
                p.close();
                
                JOptionPane.showMessageDialog(null, "Berhasil ditambah");
                
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }finally {
                loadData();
                kosong();
               setEnablefalse();
               btnaddnew.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        txtkodebarang.setText("");
        txtnamabarang.setText("");
        txtjenisbarang.setText("");
        txtharganet.setText("");
        txthargajual.setText("");
        txtstok.setText("");
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnaddnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddnewActionPerformed
        // TODO add your handling code here:
       setEnabletrue();
        btnaddnew.setEnabled(true);
    }//GEN-LAST:event_btnaddnewActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
           int i = tabelbarang.getSelectedRow();
        
        if(i == -1){
            //tidak ada baris terseleksi
            JOptionPane.showMessageDialog(this, "harap pilih data terlebih dahulu", "error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String kode_barang = (String) model.getValueAt(i, 0);
        String nama_barang = txtnamabarang.getText();
        String KJ = combobarang.getSelectedItem().toString();
        String harga_net = txtharganet.getText();
        String harga_jual = txthargajual.getText();
        String stok = txtstok.getText();
        
        try{
            
            Connection c = koneksi.getKoneksi();
            
            String sql = "UPDATE tblbarang SET NamaBarang = ?,KodeJenis = ?, HargaNet = ?, HargaJual = ? , Stok = ? WHERE KodeBarang = ?";
            
            PreparedStatement p = c.prepareStatement(sql);
            
            
                
                p.setString(1, nama_barang);
                p.setString(2, KJ);
                p.setString(3, harga_net);
                p.setString(4, harga_jual);
                p.setString(5, stok);
                p.setString(6, kode_barang);
                
            p.executeUpdate();
                p.close();
                
                JOptionPane.showMessageDialog(null,
                       "Ubah Data Berhasil");
                
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this,
                        e.getMessage());
                
            }finally{
            loadData();
            kosong();
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int i = tabelbarang.getSelectedRow();
        
        if(i == -1){
            JOptionPane.showMessageDialog(this, "Harap Pilih Data Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String kode_barang = (String) model.getValueAt(i, 0);
        
        try{
            Connection c = koneksi.getKoneksi();
            
           String sql = "DELETE FROM tblbarang WHERE KodeBarang=?";
                     
                     PreparedStatement p = c.prepareStatement(sql);
                     p.setString(1, kode_barang);
                     p.executeUpdate();
                     p.close();
                     
                     JOptionPane.showMessageDialog(null, "Hapus Data Berhasil");
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Terjadi Error"+e.getMessage());
        } finally{
            loadData();
            kosong();
        }
           
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
         dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void tabelbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelbarangMouseClicked
        // TODO add your handling code here:
        int baris = tabelbarang.getSelectedRow();
        if(baris == -1) {
            return ;
        }
        
        String kode_barang = tabelbarang.getValueAt(baris, 0).toString();
        txtkodebarang.setText(kode_barang);
        String nama_barang = tabelbarang.getValueAt(baris, 1).toString();
        txtnamabarang.setText(nama_barang);
        combobarang.setSelectedItem(tabelbarang.getValueAt(baris, 2).toString());
        String harga_net = tabelbarang.getValueAt(baris, 3).toString();
        txtharganet.setText(harga_net);
        String harga_jual = tabelbarang.getValueAt(baris, 4).toString();
        txthargajual.setText(harga_jual);
        String stok = tabelbarang.getValueAt(baris, 5).toString();
        txtstok.setText(stok);
    }//GEN-LAST:event_tabelbarangMouseClicked

    private void combobarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobarangActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_combobarangActionPerformed

    private void combobarangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combobarangItemStateChanged
        // TODO add your handling code here:
        try {
            String sql = "SELECT * FROM tbljenis WHERE KodeJenis='"+ combobarang.getSelectedItem().toString()+"'";
            
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            
            r.absolute(1);
            txtjenisbarang.setText(r.getString("Jenis"));       
        }catch (SQLException ex){
            
        }
    }//GEN-LAST:event_combobarangItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(from_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(from_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(from_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(from_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new from_barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddnew;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> combobarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelbarang;
    private javax.swing.JTextField txthargajual;
    private javax.swing.JTextField txtharganet;
    private javax.swing.JTextField txtjenisbarang;
    private javax.swing.JTextField txtkodebarang;
    private javax.swing.JTextField txtnamabarang;
    private javax.swing.JTextField txtstok;
    // End of variables declaration//GEN-END:variables
}
